### ISSUE TITLE
🐛 Example request returns table with only header and no cells

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-3d-cell-generation-api#4]
I was running the CURL example in the README but only got back an empty table. Something must have broken. I used both https://apps.humanatlas.io/api/v1/mesh-3d-cell-population and https://apfvtab7fp.us-east-2.awsapprunner.com/mesh-3d-cell-population. 

```
abueckle@******* hra-3d-cell-generation-api % curl -d '@examples/test-request.json' -H "Content-Type: application/json" -X POST https://apfvtab7fp.us-east-2.awsapprunner.com/mesh-3d-cell-population
x,y,z,Cell Type
                                                                                                                                                         
abueckle@*******hra-3d-cell-generation-api % curl -d '@examples/test-request.json' -H "Content-Type: application/json" -X POST https://apps.humanatlas.io/api/v1/mesh-3d-cell-population
x,y,z,Cell Type   
```

PS: It does work when changing the `examples/test-request.json` to use the new forma for file names (starting with `cdn`) either.

**Comment by andreasbueckle** [comment]
PS: Did some diving with @bherr2:

Folder names in `models` have `v1` appended for some reason: `https___cdn.humanatlas.io_digital-objects_ref-organ_kidney-female-left_v1`

**Comment by andreasbueckle** [comment]
PPS by @bherr2 to @LuchenCatherine  
I see why it cuts off at v1 in the directory! You are trying to trim off the .glb but you actually ended up by finding a dot and removing that afterwards for the filename, which actually removes everything past /v1.x/...

**Comment by LuchenCatherine** [comment]
I found this issue yesterday and resolved it. Will update the repo today.

**Comment by andreasbueckle** [comment]
@LuchenCatherine 
OK! Bruce put in a fix with commit https://github.com/cns-iu/hra-3d-cell-generation-api/commit/4a4c5aec64b6d2e282d0a1f246fe68a6a614055f.

**Comment by bherr2** [comment]
*temporary fix* . It looks like Lu put in a fix. Try it out @andreasbueckle I think it'll work for you.

**Comment by andreasbueckle** [comment]
Fixed with commits https://github.com/cns-iu/hra-3d-cell-generation-api/commit/f9a0cf9f80bd02356a0b826ddf10362b9ff9218c and https://github.com/cns-iu/hra-3d-cell-generation-api/commit/19b39293eda4ab81297fef3ba34a6d14f640259e.
